[2025-09-16T07:12:52.722+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-16T07:12:52.734+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: espn_news_pipeline.dbt_setup manual__2025-09-16T07:12:26.363074+00:00 [queued]>
[2025-09-16T07:12:52.736+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: espn_news_pipeline.dbt_setup manual__2025-09-16T07:12:26.363074+00:00 [queued]>
[2025-09-16T07:12:52.736+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-16T07:12:52.742+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_setup> on 2025-09-16 07:12:26.363074+00:00
[2025-09-16T07:12:52.745+0000] {standard_task_runner.py:64} INFO - Started process 160 to run task
[2025-09-16T07:12:52.751+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'espn_news_pipeline', 'dbt_setup', 'manual__2025-09-16T07:12:26.363074+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/news_pipeline.py', '--cfg-path', '/tmp/tmp95cydzfs']
[2025-09-16T07:12:52.754+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask dbt_setup
[2025-09-16T07:12:52.777+0000] {task_command.py:426} INFO - Running <TaskInstance: espn_news_pipeline.dbt_setup manual__2025-09-16T07:12:26.363074+00:00 [running]> on host d90780fea376
[2025-09-16T07:12:52.809+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='espn_news_pipeline' AIRFLOW_CTX_TASK_ID='dbt_setup' AIRFLOW_CTX_EXECUTION_DATE='2025-09-16T07:12:26.363074+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-16T07:12:26.363074+00:00'
[2025-09-16T07:12:52.809+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-16T07:12:52.815+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-16T07:12:52.816+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd $DBT_PROJECT_DIR && /home/airflow/.local/bin/dbt deps']
[2025-09-16T07:12:52.831+0000] {subprocess.py:86} INFO - Output:
[2025-09-16T07:12:52.833+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: /home/airflow/.local/bin/dbt: No such file or directory
[2025-09-16T07:12:52.833+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-09-16T07:12:52.833+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-16T07:12:52.838+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-09-16T07:12:52.840+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=espn_news_pipeline, task_id=dbt_setup, run_id=manual__2025-09-16T07:12:26.363074+00:00, execution_date=20250916T071226, start_date=20250916T071252, end_date=20250916T071252
[2025-09-16T07:12:52.846+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5 for task dbt_setup (Bash command failed. The command returned a non-zero exit code 127.; 160)
[2025-09-16T07:12:52.893+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-16T07:12:52.902+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-16T07:12:52.905+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
