[2025-08-22T17:26:27.801+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-08-22T17:26:27.807+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: espn_news_pipeline.dbt_test manual__2025-08-22T17:26:04.620259+00:00 [queued]>
[2025-08-22T17:26:27.811+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: espn_news_pipeline.dbt_test manual__2025-08-22T17:26:04.620259+00:00 [queued]>
[2025-08-22T17:26:27.811+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-08-22T17:26:27.816+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): dbt_test> on 2025-08-22 17:26:04.620259+00:00
[2025-08-22T17:26:27.820+0000] {standard_task_runner.py:72} INFO - Started process 318 to run task
[2025-08-22T17:26:27.823+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'espn_news_pipeline', 'dbt_test', 'manual__2025-08-22T17:26:04.620259+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/news_pipeline.py', '--cfg-path', '/tmp/tmpqr49atce']
[2025-08-22T17:26:27.824+0000] {standard_task_runner.py:105} INFO - Job 28: Subtask dbt_test
[2025-08-22T17:26:27.845+0000] {task_command.py:467} INFO - Running <TaskInstance: espn_news_pipeline.dbt_test manual__2025-08-22T17:26:04.620259+00:00 [running]> on host 9594dc760a36
[2025-08-22T17:26:27.881+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='espn_news_pipeline' AIRFLOW_CTX_TASK_ID='dbt_test' AIRFLOW_CTX_EXECUTION_DATE='2025-08-22T17:26:04.620259+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-22T17:26:04.620259+00:00'
[2025-08-22T17:26:27.881+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-08-22T17:26:27.887+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-22T17:26:27.887+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd $DBT_PROJECT_DIR && /home/***/.local/bin/dbt test']
[2025-08-22T17:26:27.891+0000] {subprocess.py:86} INFO - Output:
[2025-08-22T17:26:28.765+0000] {subprocess.py:93} INFO - [0m17:26:28  Running with dbt=1.8.6
[2025-08-22T17:26:29.280+0000] {subprocess.py:93} INFO - [0m17:26:29  Registered adapter: snowflake=1.8.3
[2025-08-22T17:26:29.377+0000] {subprocess.py:93} INFO - [0m17:26:29  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-08-22T17:26:29.377+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2025-08-22T17:26:29.378+0000] {subprocess.py:93} INFO - - models.espn_project.example
[2025-08-22T17:26:29.433+0000] {subprocess.py:93} INFO - [0m17:26:29  Found 7 models, 459 macros
[2025-08-22T17:26:29.434+0000] {subprocess.py:93} INFO - [0m17:26:29
[2025-08-22T17:26:29.434+0000] {subprocess.py:93} INFO - [0m17:26:29  Nothing to do. Try checking your model configs and model specification args
[2025-08-22T17:26:30.016+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-08-22T17:26:30.032+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-08-22T17:26:30.032+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=espn_news_pipeline, task_id=dbt_test, run_id=manual__2025-08-22T17:26:04.620259+00:00, execution_date=20250822T172604, start_date=20250822T172627, end_date=20250822T172630
[2025-08-22T17:26:30.055+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-08-22T17:26:30.065+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-22T17:26:30.066+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
