[2025-09-20T22:25:17.322+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-20T22:25:17.331+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: espn_news_pipeline.dbt_setup manual__2025-09-20T22:24:56.910785+00:00 [queued]>
[2025-09-20T22:25:17.333+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: espn_news_pipeline.dbt_setup manual__2025-09-20T22:24:56.910785+00:00 [queued]>
[2025-09-20T22:25:17.333+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-20T22:25:17.338+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_setup> on 2025-09-20 22:24:56.910785+00:00
[2025-09-20T22:25:17.339+0000] {standard_task_runner.py:64} INFO - Started process 102 to run task
[2025-09-20T22:25:17.341+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'espn_news_pipeline', 'dbt_setup', 'manual__2025-09-20T22:24:56.910785+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/news_pipeline.py', '--cfg-path', '/tmp/tmptyzpxz39']
[2025-09-20T22:25:17.342+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask dbt_setup
[2025-09-20T22:25:17.354+0000] {task_command.py:426} INFO - Running <TaskInstance: espn_news_pipeline.dbt_setup manual__2025-09-20T22:24:56.910785+00:00 [running]> on host 27ea88c29fa3
[2025-09-20T22:25:17.376+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='espn_news_pipeline' AIRFLOW_CTX_TASK_ID='dbt_setup' AIRFLOW_CTX_EXECUTION_DATE='2025-09-20T22:24:56.910785+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-20T22:24:56.910785+00:00'
[2025-09-20T22:25:17.376+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-20T22:25:17.381+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-20T22:25:17.381+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd $DBT_PROJECT_DIR && /home/airflow/.local/bin/dbt deps']
[2025-09-20T22:25:17.385+0000] {subprocess.py:86} INFO - Output:
[2025-09-20T22:25:17.385+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: /home/airflow/.local/bin/dbt: No such file or directory
[2025-09-20T22:25:17.385+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-09-20T22:25:17.385+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-20T22:25:17.388+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-09-20T22:25:17.389+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=espn_news_pipeline, task_id=dbt_setup, run_id=manual__2025-09-20T22:24:56.910785+00:00, execution_date=20250920T222456, start_date=20250920T222517, end_date=20250920T222517
[2025-09-20T22:25:17.394+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5 for task dbt_setup (Bash command failed. The command returned a non-zero exit code 127.; 102)
[2025-09-20T22:25:17.399+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-20T22:25:17.405+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-20T22:25:17.407+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
